config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      mount Shrine.presign_endpoint(:cache) => '/presign'

      post 'user_token' => 'user_token#create'

      resources :posts do
        collection do
          get :autocomplete
        end

        resources :audits, only: [ :index ]
      end

      resource :about, only: [ :show ], controller: 'about'
    end
  end

  constraints Clearance::Constraints::SignedIn.new(&:is_admin?) do
    mount Sidekiq::Web => '/sidekiq'
    mount Blazer::Engine, at: 'blazer'
  end

  # Authentication with Clearance
  resource :session, controller: 'clearance/sessions', only: [:create]
  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resources :users, only: [:create] do
    resource :password, controller: 'clearance/passwords', only: [:create, :edit, :update]
  end

  get    '/confirm/:user_id/:token'  => 'users#confirm',              as: 'confirm'
  get    '/sign_in'                  => 'clearance/sessions#new',     as: 'sign_in'
  delete '/sign_out'                 => 'clearance/sessions#destroy', as: 'sign_out'
  get    '/sign_up'                  => 'users#new',                  as: 'sign_up'

  resources :posts do
    resources :audits, only: [ :index ]
  end

  root to: 'posts#index'

  # Catch all to avoid FATAL error logging
  match '*path', via: :all, to: 'errors#not_found'
end

app/views/layouts/_footer.html.slim
- cache 'footer' do
  footer
    .container
      .row
        .col
          dl.row
            dt.col-md-5 Version
            dd.col-md-7= Rails.application.version
            dt.col-md-5 Build time
            dd.col-md-7= Rails.application.build_time.try(:in_time_zone)
            dt.col-md-5 Environment
            dd.col-md-7= Rails.env
        .col
          dl.row
            dt.col-md-4 Ruby
            dd.col-md-8= Rails.application.ruby_version
            dt.col-md-4 RubyGems
            dd.col-md-8= Rails.application.rubygems_version
            dt.col-md-4 Bundler
            dd.col-md-8= Rails.application.bundler_version
            dt.col-md-4 Rails
            dd.col-md-8= Rails.application.rails_version
        .col
          dl.row
            dt.col-md-5 Alpine Linux
            dd.col-md-7= Rails.application.alpine_release
            dt.col-md-5 PostgreSQL
            dd.col-md-7= Rails.application.postgresql_version
            dt.col-md-5 Redis
            dd.col-md-7= Rails.application.redis_version
            dt.col-md-5 OpenSearch
            dd.col-md-7= Rails.application.opensearch_version

app/views/layouts/_navbar.html.slim
- cache [ 'navbar', I18n.locale, current_user ] do
  nav.navbar.fixed-top.navbar-expand-md.navbar-dark.bg-dark
    .container
      a.navbar-brand href=root_path
        | DockerRails

      button.navbar-toggler {
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label=("Toggle navigation")
        data-target="#navbarSupportedContent"
        data-toggle="collapse"
        type="button"
      }
        span.navbar-toggler-icon

      #navbarSupportedContent.collapse.navbar-collapse
        ul.navbar-nav.mr-auto

        - if signed_in?
          = link_to new_post_path, \
              class: 'btn btn-primary btn-sm mr-2',
              id: 'add-new-post',
              title: 'Add new Post',
              data: { toggle: 'tooltip', placement: 'bottom' } do
            i.fa.fa-plus

          - if current_user.is_admin?
            = link_to sidekiq_web_path, \
                class: 'btn btn-light btn-sm mr-2',
                title: 'Sidekiq',
                data: { turbolinks: 'false', toggle: 'tooltip', placement: 'bottom' } do
              i.fas.fa-cogs

            = link_to blazer_path, \
                class: 'btn btn-light btn-sm mr-2',
                title: 'Blazer',
                data: { turbolinks: 'false', toggle: 'tooltip', placement: 'bottom' } do
              i.fa.fa-binoculars

          .nav-item.dropdown
            a.btn.btn-light.btn-sm.dropdown-toggle {
              aria-expanded="false"
              aria-haspopup="true"
              data-toggle="dropdown"
              href="#"
              role="button"
            }
              i.fa.fa-user-circle
              '
              = current_user.email
              '
              span.caret
            .dropdown-menu
              = link_to sign_out_path, class: 'dropdown-item', method: :delete do
                = I18n.t('layouts.application.sign_out')

        - else
          = link_to sign_up_path, class: 'btn btn-light btn-sm mr-2' do
            i.fa.fa-user-plus
            '
            = I18n.t("layouts.application.sign_up")

          = link_to sign_in_path, class: 'btn btn-light btn-sm' do
            i.fa.fa-user-circle
            '
            = I18n.t("layouts.application.sign_in")

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    title= [ title, 'DockerRails' ].compact.join(' :: ')
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'

    - if Rails.env.production? && Rails.configuration.x.plausible_script
      = javascript_include_tag Rails.configuration.x.plausible_script,
                               defer: true,
                               data: { domain: Rails.configuration.x.app_host }

  body data-controller="tooltip icons"
    = render 'layouts/navbar'

    #main
      .container
        - if alert
          p.alert.alert-danger
            = alert
        - if notice
          p.alert.alert-info
            = notice
        = yield

    = render 'layouts/footer'